name: Publish image

on:
  release:
    types: [published]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build doc the Docker image
      run: docker build docs --file Dockerfile --tag ghcr.io/demeringo/rust-serverless-ci:latest

    # - name: Tag doc the Docker image
    #   run: docker tag ghcr.io/demeringo/rust-serverless-ci:latest ghcr.io/demeringo/rust-serverless-ci:lcustom-version

    - name: Push doc images
      run: docker push -a ghcr.io/demeringo/rust-serverless-ci:latest
